sudo: required
services:
- docker
language: bash
script:
- docker version
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker-compose build
- docker run bjornmagnusson/pi-led -demo=true -num=3
- |
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    docker-compose push
  fi
env:
  global:
  - secure: pp3NQvdxiWj6TSI6+FsOZ6uA3oTHge+rTiZpScUXnT6dLOgHRwRWeCeF9gLpoEPKM233GLur5XB82XrMu+UvLbLWO00j+Yo57cOqWk0812RKKBcO1UjMkBFRS/yGsOGg32eouKDaMwwJp60aDvULmb1zwUsZcXyjObaeWN9poNV2LJT3vnOZNQvU5YB5SJtdW1thHTc1O6woN7vkCPrVS+qC3rAu3UPDz2aQep0Rwa5Yjwf8bfcMOLvfCix88yb/+hozPdRllN+EizIJvcjibadOfq6KBFKRlihXSug9RKtKZjspa0sx/o+GQM9Lb7g7B9n+PkSoPzPe2I1G6jn0XWz4vhNRKZ48cdM9HMlqbnaxUACxpoQy+mGk21WvupdZ871a3mZk2xLms8o76OAWaBAOV7Md19VY1bZd2n+Kz6S1uPXdc4GlQUBlnF12YT+77dR3WnsilTV7yfLkPE8G4QkcReE9OC6SGqH5kJO3zucW8HFTCOicUGg9phX5FqB1VZKmt3LB4XHFQjasb8/PntwCKI7K6HrGoMJ1BUpfC2hO6YsyhFlPCXZr0VcaKkhPbCaMCWk/QIyE//t+y50a3gpYXOEMJXNWqnp/z1fMJptqpgjA9/fdwW/e63fiDzJgMqhZY1xMDpSpUcNiY/9OzcRQ0wIyrNiUhaU8rCtV2k0=
  - secure: DW/YCCfQhCNqf6sA0OsAwsO2HddTaqyMkhiZC20fsAcfVCaCejvm4yCxKJZmUA7wFCnddcwH8G+6JjJc+9x3BtPURIjyWbxMFgV1OezkJg/oCSvLi2MAmmyp4si/mlODpjXUTw4UkZ3lIA/J9G0zEImkNs9ldo1+NXiKy5SLMFqI8jSQw8OiyFY/J8VsOBqefciY+0unU+WqTWoRMaBO9eA6OwJNzauabBwfMSzAPaXjcyEBgEo/UoOfAjTZePQ3s2FPopFeoBCMsiWH4vIl9jE+isbXhnatN1Mb/m/BG0NXMFjVLypMIx4FXC+4wScZdUZGpFB5LkrpVjMEIBYsTzqvkU0Dqu3yc1Ef3st5JtWBHVh+6T7B5aCjai/gZbPBmhVcYAqeZc/nesk/Euaks9C6kbtVeA9CZH5MG2HdvCWIiIU416zia5OVwM09gOzDKTskT6EYmPFeXl8BVG6I9aGC+llFDz2MPobOW+955nJhyxEM4ox9AsDn4UxOblI9PeeQ2ahtK3DyPN7JFu6fEE1nzQbuuoicJKyLKjPWAqd8ybmjJ/+N5j013O3m1H3fmsxH+nQeuH6TOLEMhvLYN4dsYtubNc3UU4CI+DX/qGtnqH0XOapCcxAJs5mNlofGJP3xK9TvI78gAuKUTVDPqpyh+msvzPe9VGlD7BNI8TI=
  - secure: t6Y9sxOaSN8YTTa0m8XPklEX6E5M701VqZX3XESAhXfVC2ePd1mHCEdP0aMOLmzSe3L9HEXDp3IISM9qdcRdkiNe60d/ON7mQ43KOKZEcVrsSK/rQgi2SjypJF4EOKBtjprzc5XvpJCCgdp+MBOplcBHp15ySIN0dV0oKSNymOQJprNQImkeT2kpCJxFzk9fpf9XneZvXsOPaFyxXHTz6lsRcx4FzzDUdnILLbcMaGF+vstrvTX6e/LhcRY9bB/7SCaE82EL1/I2tITGB1gpQi2LC/urnI+hAneiyWT4YEIV42QPhJoUdzT89DFYUOjcgbJe7cAC0KK1QVBAkdbeagHSebN/CARvCwmJWJVHf8xW4kwKTkjoE8r5wYbFZyOCpv2FaaYpP84Z5+LdDfLvtSdcoLZFCalOcNKS9mFztv4AE0gmF4qLScUJ1lsXTX64rGkH33wjjDiyMx92TbyW+F4EghKU62lAM5HRx92P8v7aMxlbzcJCHSaamZoUSua8PJCfAshXtLmYd/qYDr5t5O6rsKCKe9Z/+0AXYaV3Hfq1VALr4KqbzuzMAXxSOV+8iTT/gp+KAsViRxhuP62u07yBPdiRblmY2qCA2cvT/ogUpAmMVz/ECyiRs01f20e84j0hArBN6lsrNY1zqtbfZARrolzV2ebftFLxqymUyWg=
before_install:
- sudo mkdir -p ~\/.ssh
- sudo touch ~\/.ssh/id_rsa
- sudo touch ~\/.ssh/known_hosts
- sudo openssl aes-256-cbc -K $encrypted_ce8f5f305d9b_key -iv $encrypted_ce8f5f305d9b_iv -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- sudo cat resinkey >> ~\/.ssh/known_hosts
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      git remote add resin $RESIN_REMOTE
      git push resin master
    fi
