version: '3'
services:
  api:
    image: bjornmagnusson/pi-led
    build:
      context: .
    command: -demo=true -api=true -num=0
    ports:
      - "8080:8080"
    deploy:
      placement:
        constraints:
          - node.hostname == pi1
