version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment:
          DOCKER_IMAGE_NAME: bjornmagnusson/pi-led
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Build Docker image
          command: |
            docker version
            docker container run --rm --privileged multiarch/qemu-user-static:register --reset
            apk --verbose add --no-cache bash
            ./build.sh
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              ./build.sh ${CIRCLE_TAG}
            fi
      - run:
          name: Test examples
          command: |
            docker container run ${DOCKER_IMAGE_NAME} -demo=true -num=3
      - deploy:
          name: Push Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker image push ${DOCKER_IMAGE_NAME}
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker image push ${DOCKER_IMAGE_NAME}:${CIRCLE_TAG}
            fi
  deploy:
    docker:
      - image: bjornmagnusson/resinio-client
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Authenticate to balena-cloud
          command: |
            balena login --token $RESIN_TOKEN
      - deploy:
          name: Deploy to balena cloud (pi1led)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              balena deploy pi1led
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              balena deploy pi1led
            fi
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DOCKER_HUB
          filters:
            branches:
              ignore: master
  build_deploy:
    jobs:
      - build:
          context: DOCKER_HUB
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - deploy:
          requires:
            - build
          context: RESIN_IO
          filters:
            tags:
              only: /.*/
            branches:
              only: master
